# Data Cleaning

In [11]:
import pandas as pd

#Adding date column in twitter data

#tweets = pd.read_csv("C:/Users/MB-PC/ML/tweets_cardano.csv")
#tweets['Date'] = pd.to_datetime(tweets['Date']).dt.date #adding Date column in the data set

#tweets.to_csv('Ethereum_tweets_with_date.csv') #Saving the required file

#importing Data from reddit saved

#importing Data from twitter saved


tweets = pd.read_csv("Cardano_tweets_with_date.csv")
reddit = pd.read_csv("Cardano_reddit_with_date.csv")
tweets = tweets.drop('Unnamed: 0',axis= 1 )
reddit = reddit.drop('Unnamed: 0', axis =1)
tweets = tweets.drop('Unnamed: 0.1', axis = 1)
reddit = reddit.drop(['title', 'score', 'url'], axis= 1)
reddit = reddit.drop('num_comments', axis =1)
tweets = tweets.drop(['User', 'Likes', 'Retweet'], axis = 1)

#concating the two files

#combined_data = pd.concat([tweets, reddit],ignore_index=True)
#exporting
#combined_data.to_csv("Combined_reddit_tweets_cardano")

In [14]:
tweets.dropna()

           Date                                            Content
0    2023-03-27  Remember when you could mint a #Cardano projec...
1    2023-03-25  . @Cointelegraph Clueless or malicious?\n3 maj...
2    2023-03-19  Compared to Bitcoin or Ethereum, in Cardano we...
3    2023-02-28  Last year I made over 1,000 TXs on Cardano cos...
4    2023-02-28  Ponzinomics -\n\nOr why most yield in blockcha...
..          ...                                                ...
131  2020-07-20  üì£üì£ $150 #Cardano vs #Chainlink Giveaway!!üéÅüéÅ\n\...
132  2020-05-25  #Cardano development company will be joining t...
133  2020-02-07  üö® RT Giveaway üö®\n\nTo celebrate our growth we ...
134  2019-10-23  The #Cardano Foundation has teamed up with @CO...
135  2019-03-12  In 2019, what is your preferred #crypto? \nPic...

[136 rows x 2 columns]

In [13]:
reddit = reddit.dropna()

In [15]:
reddit

           Date                                               body
0    2021-02-19  # Welcome!\n\nA warm welcome from the Cardano ...
1    2023-04-27  Hello everyone,\n\nWelcome to the Cardano Dail...
4    2023-04-26  Hello Cardano Family!\n\n&#x200B;\n\nThis is E...
6    2023-04-26  Two years in Cardano and I‚Äôm finally getting b...
7    2023-04-27  Is it necessary to revoke or limit smart contr...
..          ...                                                ...
865  2023-02-17  So, I made this game a while ago but I don't t...
866  2023-02-17  Hey Everyone!\n\nLet‚Äôs go‚Ä¶.\n\nNewly Covered T...
869  2023-02-17  Hello everyone,\n\nWelcome to the Cardano Dail...
870  2023-02-17  [https://worldmobile.co.tz/](https://worldmobi...
872  2023-02-17  Hello: Tax season time in USA and I'm having s...

[497 rows x 2 columns]

In [16]:
reddit = reddit.rename(columns = {'body': 'Content'})

In [17]:
#concating the two files

combined_data = pd.concat([tweets, reddit],ignore_index=True)
#exporting

combined_data.to_csv("Combined_reddit_tweets_cardano.csv")

In [10]:
#reddit.to_csv("Combined_reddit_tweets_polkadot.csv")

In [1]:
import pandas as pd 
reddit = pd.read_csv("Polkadot_reddit_extraction_101.csv")

In [3]:
reddit = reddit.dropna()

,Unnamed: 0,Body,Date
2,2,# Polkadot News\n\nRegistration for Polkadot D...,2023-05-12 07:05:14
4,4,"# Polkadot News\n\nDaniel Schoenberger, Chief ...",2023-05-11 07:34:58
5,5,Hi I moved some DOT to my mobile wallet to sta...,2023-05-10 06:54:35
8,8,"# Polkadot News\n\nReferendum 114, proposing t...",2023-05-10 09:10:44
9,9,How do I install Talisman on Brave? I just don...,2023-05-10 07:37:25
...,...,...,...
958,958,"# Polkadot News\n\nReferendum 80, seeking suff...",2022-11-08 09:20:02
960,960,I‚Äôm interested in staking my DOT and am wonder...,2022-11-07 17:31:07
968,968,# Polkadot News\n\nAjuna Network has won the m...,2022-11-07 10:16:08
973,973,I have a staked with polkadot js this is my fi...,2022-11-05 20:47:46
975,975,I'll temper my excitement until the SEC confir...,2022-11-05 17:05:07